#!/usr/bin/env bash

turkish="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=tr&dt=t&q=$(xsel -o | sed ':a;N;$!ba;s/\n/ /g' | sed "s/[\"'*&-<>]//g")" | sed "s/,,,0]],,.*//g" | awk -F'"' '{print $2, $6}')"
turkishfull=$(echo $turkish | rev | cut -d ' ' -f2,3- | rev )

notify-send --icon=info "$(xsel -o | sed ':a;N;$!ba;s/\n/ /g' )" "$turkishfull"
